### ISSUE TITLE
Syncing playlists across computers

### ISSUE THREAD

**Issue by CurtisBlankstein** [gilbarbara/Turntable.fm-Playlists#1]
It should be possible to sync playlists across multiple computers. Barring this, at least easily exporting playlist so as to sync them by some other means, say, Dropbox would work too. I primarily use Turntable.fm on a computer that is not the computer I discovered this extension and populated all my playlists, and I don't want to have to rebuild them all again. That's hundreds of songs to go through.

**Comment by gilbarbara** [comment]
I'll look into that soon! Probably using dropbox or at least a simple copy/paste!

**Comment by gilbarbara** [comment]
There a new version with Backup / Restore options.

[s]
