### ISSUE TITLE
Problem when using Playlist with Turntable+ extension

### ISSUE THREAD

**Issue by raptorkarl** [gilbarbara/Turntable.fm-Playlists#11]
For some reason when TT+ loads with the Playlist extension it makes the Playlist window shorter -- could you just add a permanent scroll bar to the main listing of playlists?

Thanks!
--Raptor

**Comment by gilbarbara** [comment]
Hey raptorkar.
How are you?

I've seen that too and I've notified the TT+ developer about this bug some time ago. :/
I made a simple Users List for turntable.fm if you want to check it out.
https://github.com/gilbarbara/ttRoomie

[s]
