### ISSUE TITLE
How in the world do you save your playlists?

### ISSUE THREAD

**Issue by mskrista** [gilbarbara/Turntable.fm-Playlists#15]
I am using Chrome, and I love your extension, however it never saves my playlists. I create them while DJing, but when I leave and come back, they're gone. Thanks.

**Comment by gilbarbara** [comment]
hello mskrista.
How are you?

Sorry about the delay.
It save the data in a localStorage object in Chrome. It's kinda like a cookie but larger.
As cookies you can erase them when using "Clear Browser Data" in Chrome.
If that's the case, please turn off "Delete cookies and other site and plug-in data" when cleaning.
Also when using Incognito, Chrome don't save any user data.

You also can use Dropbox for online storage. It's free and works great.
This way your data is synced every time you change a playlist and can be synced in any computer.

**Comment by mskrista** [comment]
Okay Gil thanks. I'm using Dropbox and it works great as you said.
