### ISSUE TITLE
Songs "disappear" from my playlist

### ISSUE THREAD

**Issue by jeffreysteinke** [gilbarbara/Turntable.fm-Playlists#17]
I've noticed this a couple times now but can't tell when it's actually happening.  What does happen though is that songs I've added to a playlist loose their tag.  They stay in my TT queue though.  The easiest way I notice is that the # of songs (e.g. My Playlist (27)) decreases, and then sure enough the songs are no longer tagged.

I have TT+ & TT Extended also installed, but only TT+ is Enabled (TT Ext is disabled).

This error has happened BOTH when I'm syncing with dropbox & when I'm not.

I also feel like this typically only happens for the playlist I currently have selected, but that could just be what's most easiest to notice.

My stats:
- 15 playlists
- 311 songs in my playlists
- 514 sons played
- 331 songs in queue
- Installed 7/2/11
- V 0.961

I haven't been able to reproduce it with any sort of consistency so not really sure how best to trouble shoot.  Open to suggestions though and glad to try & help.

**Comment by gilbarbara** [comment]
hey!

Try to keep track of your playlists and see if this happens with any playlists or just some.
Maybe a daily screen capture of the open menu?

Can you use Playlists with TT+? It was too buggy for me

I made a simple Users List if you want to check it out.
https://github.com/gilbarbara/ttRoomie

**Comment by jeffreysteinke** [comment]
Cool - I'll start keeping screen shots of the list of playlists.  For what it's worth I really only use 2-3 of the playlists regularly.

I haven't had many problems using Playlists with TT+.  The main issue is that at times my Playlists container will shrink to about 1/2 it's size, although it's really only cut off visibly.  By this I mean the scroll bar keeps going down so the full playlist container is there, but I can only see the top half.  Make sense?  This only happens when I have TT+ extended.  It happens irregularly so if it happens again I'll add a screengrab.  

I added ttRoomie and this is awesome.  In fact it's 95% of what I'm looking for, short of just a couple things:
- Keyword notifications
- AFK timing

Honestly the AFK timing isn't even that important.  The keyword notification is though (to me at least).  Nice work Gil.

**Comment by theschles** [comment]
I'm having a simliar issue: https://github.com/gilbarbara/Turntable.fm-Playlists/issues/16

Might I suggest grabbing a daily export after startup and diffing them from the previous day?  See my post.  FYI great JSON formatter: http://jsonformatter.curiousconcept.com/

**Comment by jeffreysteinke** [comment]
I haven't been on TT for a few days but I'll try & do that as well.  Thanks @theschles.
