### ISSUE TITLE
Non-expanding playlist makes for viewing issues. Need to reinstall? Help please :[

### ISSUE THREAD

**Issue by cygvis** [gilbarbara/Turntable.fm-Playlists#19]
Is there a reason i can't expand my playlist or scroll normally (on left side)?

http://imgur.com/yWA33

I'm running Chrome. This problem seemed to come about as soon as I installed TT+

**Comment by gilbarbara** [comment]
Hello!
Yeah, that is TT+ bug. I already notified the TT+ developer.

You can send him a message too! http://turntableplus.fm/beta

[s]
