### ISSUE TITLE
need to reinstall?

### ISSUE THREAD

**Issue by ghost** [gilbarbara/Turntable.fm-Playlists#2]
I can't create a playlist with the app for Turntable in Chrome. How  can I re-install?

**Comment by gilbarbara** [comment]
hey j4hawg! 
You can remove the extension and try to install again.
which version of Chrome?

**Comment by ghost** [comment]
Thanks! Chrome 12.0.742.112. Uninstalled & reinstalled, but same result. Can change all screens/pages in extension. but can't drag or type in it.

**Comment by ghost** [comment]
Didn't work. Still can't drag or type. Chrome version12.0.742.112.

--- On Fri, 7/8/11, gilbarbara reply@reply.github.com wrote:

**Comment by gilbarbara** [comment]
hey!
Did your clean your cache?

Try to disable other extensions to see if there's a conflict.

Reset your chrome data folder.
BEWARE, this will remove all your preferences, bookmarks, etc. Sync your chrome with your gmail account first.
