### ISSUE TITLE
Can no longer add to playlist

### ISSUE THREAD

**Issue by davidneedham** [gilbarbara/Turntable.fm-Playlists#20]
I've used this extension for several months without any problems. Sometime around Christmas I became unable to add any more songs to my playlists. I drag them from my queue over to the playlist, but it doesn't go anywhere. 

I've tried disabling the extension and trying again with no luck. I haven't tried removing the extension and reinstalling yet because I don't want to lose my playlists. Any ideas?

**Comment by davidneedham** [comment]
I still cannot add any songs to that particular playlist. But I can create new playlists and add songs into those.

**Comment by cokeclassic019** [comment]
Same bug here. I cannot add songs to just one of my playlists. I have ttTools and TT+ not sure if that effects it.

**Comment by geekonabike** [comment]
I have this issue when I get too many tracks in a playlist (150+)  & I become unable to delete tracks. A nice feature would be the ability to delete an entire playlist so as to start oven w/ smaller sub genres.
 For a work around now I'm unlinking dropbox, manually editing tracks out of the dropbox playlist file, pasting a manual playlist recovery, dropbox then seems to reconnect on it's own or you can reconnect it yourself.

**Comment by geekonabike** [comment]
Update: It now seems I can have less the 70 tracks per playlist & still have the ability to delete a track from playlist without resorting to the editing described in the above post.
 It have to do w/ total tracks in all playlist, or # of tracks in the TT.fm playlist????
