### ISSUE TITLE
Playlists keep refreshing.

### ISSUE THREAD

**Issue by GotMilk6** [gilbarbara/Turntable.fm-Playlists#21]
After awhile some playlists get corrupted and they keep automatically refreshing about every 10 seconds, and I can no longer add to them or delete from them. If I have these particular playlists open, they cause turntable to freeze for a second every time it refreshes, which causes lag. Is there anyway to fix this? Removing then re-installing doesn't help.

**Comment by gilbarbara** [comment]
hey!
That's weird.. Which browser are you using? Do you use Dropbox sync for back-up?
The app uses the browser localStorage to keep the playlists between session: localStorage.TFMPL
You can access it within the Javascript Console  and if you really want to erase it, try "delete localStorage.TFMPL"

**Comment by GotMilk6** [comment]
I use Chrome for Turntable and I do have dropbox sync for back up, but the first time this happened, I don't believe I had dropbox synced. I'll try your recommendation though, thank you.
