### ISSUE TITLE
Playlist is broken..

### ISSUE THREAD

**Issue by gilbarbara** [gilbarbara/Turntable.fm-Playlists#26]
So...

Turntable changed the way they show the queue (for the better) by adding to the page just a short list of songs instead of your entire playlist.
But unfortunately the method I used when I created this extension was non-intrusive and only cloned the songs from the queue to the playlist manager. That's why he worked so long..

I'm still thinking if it's worth having to rewrite the extension and become dependent on any changes they make in the code.

Any ideas?

**Comment by lucasdailey** [comment]
I do hope you fix it, I love the extension and feel lost DJing without it!

**Comment by gabrielpreston** [comment]
This is the plugin I use the absolute most for TT, I will be heartbroken if it stays broken.

**Comment by TankGirl** [comment]
Agreed, this is my most used extension. Please please fix it!! I'm so lost without it.

**Comment by djshadowrunner** [comment]
I'm casting another vote in favor of a fix. Thanks very much for your efforts til now on such a great extension; I would love  for it to be functional again!

**Comment by Psykoral** [comment]
TTFM has been much harder to use without this addon. I hope there's some time and resources available to fix the Playlist extension! If you're willing

**Comment by Psykoral** [comment]
OMG YOU RULE! Thank you for fixing this! TTFM is whole again :cD

**Comment by lucasdailey** [comment]
It's previewing songs again! But I can't drag to add songs to a playlist, is there another method or is that part of it not working yet?

Excited to see the progress!

**Comment by TankGirl** [comment]
Woohoo!!! At least the stuff I already had categorized is easily accessible now. I can't wait for it to be fully functional again!

**Comment by TroyMcClure** [comment]
Please update this.  I just discovered this, and would LOVE to give it a try when its working!

**Comment by Psykoral** [comment]
Just committed an update for Gil's review to at least get the Playlist visually functional again. There's still work to be done to get it to be able to drag songs over from your queue to a playlist, but on this first run I at least made it possible to use this extension with playlists you've already had setup. I guess in the meantime you could manually add songs to the playlist.json by finding it's song ID, if you were so inclined. 

If you'd like to give my fixes a preview, just run this in your Chrome console (F12, console tab). This will grab and apply the CSS file I sent to Gil for review, so at least you can test it out while he reviews my changes.

*\* Update*\* Looks like Github's comments doesn't like my link tag. Fixed!

$("&lt;link/&gt;", {rel: "stylesheet",type: "text/css",href: "https://dl.dropbox.com/u/55701302/ttfm_playlist/playlists.css"}).appendTo("head");
