### ISSUE TITLE
Update for new TT layout?

### ISSUE THREAD

**Issue by gruvmyster01** [gilbarbara/Turntable.fm-Playlists#27]
Hey I was just wondering if anyone was working on updating Playlist Manager to work with the new TT layout.  The playlist window has a tendency to become either hidden under the queue/chat window and even if split out with TurnTable+ or TurnTableX the window still remains partially and sometimes totally hidden forcing the user to have to zoom in on the page to see it (at which point the ability to change your playlist is no longer available you can only preview songs on the playlist you're already on at that point.

**Comment by JaNoll** [comment]
Amen. I would love to be able to use this app again. It is by far my favorite.

**Comment by Psykoral** [comment]
As far as positioning goes, in the meantime you can use this code to adjust the location of the playlist as well as bring it to the "front" HTML layer. 

Open your JavaScript console (F12 on most browsers) and type this in: 
$('#TFMPL').css('top', '65px').css('left', '35px').css('z-index', '3');

Or make it a bookmark for easy, repeated access. Add a bookmark with the following:
javascript: $('#TFMPL').css('top', '65px').css('left', '35px').css('z-index', '3');

Adjust the top and left settings to your liking/browser size.
