### ISSUE TITLE
Location of Files in Lion

### ISSUE THREAD

**Issue by cordisco** [gilbarbara/Turntable.fm-Playlists#3]
I performed a clean install of Lion on a new drive, and reinstalled Chrome.  Chrome automatically reinstalled my extensions, but not my playlist files.

I have the original playlist files on my old drive, but I can't locate a place to move them to on the new drive.  Put simply, the location of where Lion installs Chrome Extensions has changed.  Any idea of where I should move the files to in order to regain my playlists?

Any help would be appreciated.  Great extension!

**Comment by gilbarbara** [comment]
Hey cordisco.
Sorry about the delay.
Have you fixed your problem?
I have a new version with dropbox support ready but I'm waiting for them to approve my app.

[s]

**Comment by cordisco** [comment]
I just started over.  No problems.  Thanks for replying.  GREAT app!
