### ISSUE TITLE
Suggestion - Playlist sort

### ISSUE THREAD

**Issue by dvillega** [gilbarbara/Turntable.fm-Playlists#4]
Could we get a playlist sort by song title, band name, or other metadata?  Otherwise fantastic stuff.

**Comment by TeamTeamUSA** [comment]
Hey Gil,

Are you working on this‽ If not I can get at least a basic sort by song title working and have forked with the idea of doing this.

Lemme know, so we don't duplicate efforts.

Go!

=ml=

**Comment by TeamTeamUSA** [comment]
Hey Gil,

I sent a pull request for a version with sortable playlists.

Let me know if you have any issues.

Go!

=ml=

**Comment by dvillega** [comment]
Sort is now included.
