### ISSUE TITLE
Syncing playlist with some cloud account automatically

### ISSUE THREAD

**Issue by predikt** [gilbarbara/Turntable.fm-Playlists#5]
just suggesting to see if there's a way to sync with some account (maybe Google) so whatever computer you're on while logged into your account in Chrome, it will automatically pull up your playlist.  I did the copy and paste but if I update the playlist on another machine, i have to carry this preferences file with me. Hard to manage.

**Comment by gilbarbara** [comment]
Hey predikt!
I have a new version ready waiting for dropbox to approve my app.

[s]

**Comment by predikt** [comment]
Fantastic!  This app works great gilbarbara. Looking forward to it. You're
inspiring me to make some extensions :)
