### ISSUE TITLE
Playlist Sort

### ISSUE THREAD

**Issue by davemannr15** [gilbarbara/Turntable.fm-Playlists#6]
I agree that a playlist sort would make this already GREAT addition to turntable much, much better!  Alphabetically by song title or artist, or something like that... anything to help sort long playlists would be great!

**Comment by gilbarbara** [comment]
Hey Dave!

Sorting is available in the new version!

Thanks

**Comment by davemannr15** [comment]
Awesome!!!

This is great!  I love it!  Thanks for the update!

Dave
