### ISSUE TITLE
problem with dropbox authorization

### ISSUE THREAD

**Issue by jonathanpeterson** [gilbarbara/Turntable.fm-Playlists#8]
First - great extension, thanks.

I was on the decks the first time I tried doing the dropbox sync and the page loaded off TT.  I hit the back button and reloaded to get back up as DJ, so I never logged into drop box to authorize the extension on my work PC.

I successfully connected to dropbox from my home PC no problem.

Now the auth is stuck on the work PC - it must have partial transaction stored somewhere, I've uninstalled the extension and re-installed and I just get a spinning "in progress" indicator saying authorizing, or if I click the "connect box" saying connecting to drop box.

**Comment by gilbarbara** [comment]
hey Jonathan!
Thanks!

I'll add a button to reset the authentication, but I think you can delete
the cookie from TFMPL in turntable.fm domain to reset

[s]
